// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_iteration_jaccard_cpp
List compute_iteration_jaccard_cpp(IntegerMatrix rho_A, IntegerMatrix rho_B);
RcppExport SEXP _BayRC_compute_iteration_jaccard_cpp(SEXP rho_ASEXP, SEXP rho_BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_A(rho_ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_B(rho_BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_iteration_jaccard_cpp(rho_A, rho_B));
    return rcpp_result_gen;
END_RCPP
}
// permutation_jaccard_cpp
NumericVector permutation_jaccard_cpp(IntegerMatrix rho_A, IntegerMatrix rho_B, int n_perm, int seed);
RcppExport SEXP _BayRC_permutation_jaccard_cpp(SEXP rho_ASEXP, SEXP rho_BSEXP, SEXP n_permSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_A(rho_ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_B(rho_BSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_jaccard_cpp(rho_A, rho_B, n_perm, seed));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_jaccard_cpp
List bootstrap_jaccard_cpp(IntegerMatrix rho_A, IntegerMatrix rho_B, int n_boot, int seed);
RcppExport SEXP _BayRC_bootstrap_jaccard_cpp(SEXP rho_ASEXP, SEXP rho_BSEXP, SEXP n_bootSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_A(rho_ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_B(rho_BSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_jaccard_cpp(rho_A, rho_B, n_boot, seed));
    return rcpp_result_gen;
END_RCPP
}
// compute_gain_loss_iterations_cpp
List compute_gain_loss_iterations_cpp(IntegerMatrix rho_A, IntegerMatrix rho_B);
RcppExport SEXP _BayRC_compute_gain_loss_iterations_cpp(SEXP rho_ASEXP, SEXP rho_BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_A(rho_ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_B(rho_BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gain_loss_iterations_cpp(rho_A, rho_B));
    return rcpp_result_gen;
END_RCPP
}
// gainloss_pvalue_iterations_cpp
double gainloss_pvalue_iterations_cpp(IntegerMatrix rho_A, IntegerMatrix rho_B, int n_perm, int seed);
RcppExport SEXP _BayRC_gainloss_pvalue_iterations_cpp(SEXP rho_ASEXP, SEXP rho_BSEXP, SEXP n_permSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_A(rho_ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rho_B(rho_BSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gainloss_pvalue_iterations_cpp(rho_A, rho_B, n_perm, seed));
    return rcpp_result_gen;
END_RCPP
}
// compute_null_congruence_cpp
NumericVector compute_null_congruence_cpp(IntegerVector pathway_idx, LogicalVector rhythmic_A, LogicalVector rhythmic_B, int n_perm, int seed);
RcppExport SEXP _BayRC_compute_null_congruence_cpp(SEXP pathway_idxSEXP, SEXP rhythmic_ASEXP, SEXP rhythmic_BSEXP, SEXP n_permSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pathway_idx(pathway_idxSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type rhythmic_A(rhythmic_ASEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type rhythmic_B(rhythmic_BSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_null_congruence_cpp(pathway_idx, rhythmic_A, rhythmic_B, n_perm, seed));
    return rcpp_result_gen;
END_RCPP
}
// compute_null_congruence_cpp_v2
NumericVector compute_null_congruence_cpp_v2(IntegerVector pathway_idx, LogicalVector rhythmic_A, LogicalVector rhythmic_B, int n_perm);
RcppExport SEXP _BayRC_compute_null_congruence_cpp_v2(SEXP pathway_idxSEXP, SEXP rhythmic_ASEXP, SEXP rhythmic_BSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pathway_idx(pathway_idxSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type rhythmic_A(rhythmic_ASEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type rhythmic_B(rhythmic_BSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_null_congruence_cpp_v2(pathway_idx, rhythmic_A, rhythmic_B, n_perm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayRC_compute_iteration_jaccard_cpp", (DL_FUNC) &_BayRC_compute_iteration_jaccard_cpp, 2},
    {"_BayRC_permutation_jaccard_cpp", (DL_FUNC) &_BayRC_permutation_jaccard_cpp, 4},
    {"_BayRC_bootstrap_jaccard_cpp", (DL_FUNC) &_BayRC_bootstrap_jaccard_cpp, 4},
    {"_BayRC_compute_gain_loss_iterations_cpp", (DL_FUNC) &_BayRC_compute_gain_loss_iterations_cpp, 2},
    {"_BayRC_gainloss_pvalue_iterations_cpp", (DL_FUNC) &_BayRC_gainloss_pvalue_iterations_cpp, 4},
    {"_BayRC_compute_null_congruence_cpp", (DL_FUNC) &_BayRC_compute_null_congruence_cpp, 5},
    {"_BayRC_compute_null_congruence_cpp_v2", (DL_FUNC) &_BayRC_compute_null_congruence_cpp_v2, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayRC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
