# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_iteration_jaccard_cpp <- function(rho_A, rho_B) {
    .Call(`_BayRC_compute_iteration_jaccard_cpp`, rho_A, rho_B)
}

permutation_jaccard_cpp <- function(rho_A, rho_B, n_perm, seed = 12345L) {
    .Call(`_BayRC_permutation_jaccard_cpp`, rho_A, rho_B, n_perm, seed)
}

bootstrap_jaccard_cpp <- function(rho_A, rho_B, n_boot, seed = 12345L) {
    .Call(`_BayRC_bootstrap_jaccard_cpp`, rho_A, rho_B, n_boot, seed)
}

compute_gain_loss_iterations_cpp <- function(rho_A, rho_B) {
    .Call(`_BayRC_compute_gain_loss_iterations_cpp`, rho_A, rho_B)
}

gainloss_pvalue_iterations_cpp <- function(rho_A, rho_B, n_perm, seed = 12345L) {
    .Call(`_BayRC_gainloss_pvalue_iterations_cpp`, rho_A, rho_B, n_perm, seed)
}

compute_null_congruence_cpp <- function(pathway_idx, rhythmic_A, rhythmic_B, n_perm = 1000L, seed = 123L) {
    .Call(`_BayRC_compute_null_congruence_cpp`, pathway_idx, rhythmic_A, rhythmic_B, n_perm, seed)
}

compute_null_congruence_cpp_v2 <- function(pathway_idx, rhythmic_A, rhythmic_B, n_perm = 1000L) {
    .Call(`_BayRC_compute_null_congruence_cpp_v2`, pathway_idx, rhythmic_A, rhythmic_B, n_perm)
}

